"""
schemas/behaviours.py — Detected Behaviours API schemas.

Object ownership:
    EvidenceItem        Owned by: evidence layer (app/evidence/)
                        Consumer: BehaviourDetail
    BehaviourDetail     Owned by: behaviour service (app/services/behaviour_service.py)
                        Consumer: BehavioursResponse, BehaviourProfile
    BehaviourProfile    Owned by: behaviour service
                        Consumer: AI coach, decision engine, plan service
    BehavioursResponse  Owned by: API layer (app/api/behaviours.py)
                        Consumer: Frontend Behaviour Report page
"""

from __future__ import annotations

from typing import List
from pydantic import Field
from app.schemas.common import BaseResponse, SeverityLevel, BiasType


class EvidenceItem(BaseResponse):
    """
    A single transaction that constitutes evidence for a detected behaviour.

    Fields:
        transaction_id  Database ID of the supporting Transaction row.
        date            ISO 8601 date string (YYYY-MM-DD).
        description     Original transaction narration / description.
        amount          Signed amount in session currency (negative = debit).
        category        Spending category assigned to this transaction.
        explanation     Human-readable explanation of WHY this transaction
                        is evidence of the bias (generated by detector).
    """

    transaction_id: int = Field(description="DB id of the supporting transaction.")
    date: str = Field(description="Transaction date (YYYY-MM-DD).")
    description: str = Field(description="Original transaction narration.")
    amount: float = Field(description="Signed amount; negative = debit.")
    category: str = Field(description="Assigned spending category.")
    explanation: str = Field(description="Why this transaction supports the bias.")


class BehaviourDetail(BaseResponse):
    """
    Full detail record for a single detected behavioural bias.

    Fields:
        id              Database ID of the DetectedBehaviour row.
        bias_type       Canonical bias identifier (from BiasType enum).
        display_name    Human-readable name for the bias.
        confidence      Detector confidence score 0.0–1.0.
        severity        Impact severity: low | medium | high.
        detected        Always True in this response (False results are filtered).
        summary         Plain-English description of what was detected and why.
        evidence        List of up to 5 supporting transactions.
    """

    id: int
    bias_type: BiasType = Field(description="Canonical bias identifier.")
    display_name: str = Field(description="Human-readable bias name.")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence 0.0–1.0.")
    severity: SeverityLevel = Field(description="Impact severity level.")
    detected: bool = Field(default=True, description="Always True in API responses.")
    summary: str = Field(description="Plain-English detection summary.")
    evidence: List[EvidenceItem] = Field(
        default_factory=list,
        description="Up to 5 supporting transaction records.",
    )


class BehaviourProfile(BaseResponse):
    """
    Aggregate behavioural profile for a session.

    This is the internal transfer object passed from the behaviour layer
    to the decision engine, coach service, and plan service.
    It is NOT directly exposed via API — BehavioursResponse is the API model.

    Fields:
        session_id          UUID of the parent upload session.
        dominant_bias       The highest-confidence detected bias, or None.
        all_biases          All detected biases (detected=True only).
        overall_risk_level  Aggregate risk based on bias severity mix.
    """

    session_id: str
    dominant_bias: BiasType | None = Field(
        default=None, description="Highest-confidence bias, or None if none detected."
    )
    all_biases: List[BehaviourDetail] = Field(default_factory=list)
    overall_risk_level: SeverityLevel = Field(default=SeverityLevel.LOW)


class BehavioursResponse(BaseResponse):
    """
    API response for GET /behaviours/{session_id}.

    Fields:
        session_id      UUID of the upload session.
        behaviours      All detected biases, sorted by confidence descending.
        total_count     Total number of biases detected (len of behaviours list).
    """

    session_id: str
    behaviours: List[BehaviourDetail] = Field(
        default_factory=list,
        description="Detected biases, sorted by confidence descending.",
    )
    total_count: int = Field(default=0, description="Number of detected biases.")

